local function extinguish(self, handle, elapsed)
	go.delete(go.get_parent())
	go.delete()
end

local function loop(self, url, property)
	go.animate(go.get_parent(), "scale.y", go.PLAYBACK_LOOP_PINGPONG, 0.9, go.EASING_INOUTCUBIC, 0.2)
end

function init(self)
	go.set(go.get_parent(), "scale.y", 0)
	go.animate(go.get_parent(), "scale.y", go.PLAYBACK_ONCE_FORWARD, 1, go.EASING_INOUTCUBIC, 0.3, 0, loop)
	timer.delay(30, false, extinguish)
end