local gamestate = require("data.gamestate")

function init(self)
	msg.post(".", "acquire_input_focus")
	self.title = gui.get_node("title")
	self.playbutton = gui.get_node("playbutton")
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		if gui.pick_node(self.playbutton, action.x, action.y) then
			gamestate.has_game_started = true
			msg.post(".", "move_up")
		end
	end
end