local cursor = require("in.cursor")

function init(self)
	msg.post(".", "acquire_input_focus")
	self.next_pos = vmath.vector3()

	-- anything that's not in the object_drag collision group can't be dragged
	-- cursor.listen(msg.url("#cursor"), cursor.DRAG_START, function(message_id, message)
	-- 	if message.group ~= hash("object_drag") then
	-- 		return true
	-- 	end
	-- end)
end

function on_input(self, action_id, action)
	if action_id == nil then
		self.next_pos = vmath.vector3(action.x, action.y, 0)
	end
end

function update(self, dt)
	go.set_position(self.next_pos)
end